version: '3.8'

services:
 nginx:
   build: ./nginx
   ports:
     - "8080:80"
   volumes:
     - static_volume:/home/app/locallibrary/staticfiles
   depends_on:
     - app
 app:
   build:
     context: .
     dockerfile: Dockerfile
   volumes:
     - static_volume:/home/app/locallibrary/staticfiles
   env_file:
     - .env
   expose:
     - 8000

volumes:
 static_volume:
