version: '3.7'

services:
  web:
    container_name: library
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
#  nginx:
#    container_name: library-nginx
#    build: ./nginx
#    ports:
#    - "8888:80"
#    depends_on:
#      - web
